language: python
matrix:
  include:
    - os: linux
      python:
        - 2.7
        - 3.6
    - os: osx
      python: 3.6
env:
- PKG_NAME=limix_lmm
script:
- bash <(curl -fsSL https://raw.githubusercontent.com/horta/ci/master/travis.sh)
notifications:
  email:
    recipients:
    - fncpaolo.casale@gmail.com
    on_success: never
    on_failure: always
